set(GAME_FOLDER_${TARGET_SDK} ${GAME_FOLDER_DEFAULT_${TARGET_SDK}} CACHE STRING "The location of your ${TARGET_SDK} game folder.")
option(INSTALL_TO_GAME_FOLDER_${TARGET_SDK} "Install to ${FRIENDLY_GAME_NAME_${TARGET_SDK}} game folder" ON)
set(MOD_TARGET mod-${TARGET_SDK})
set(UPDATE_SERVER_NAMESPACE ${UPDATE_SERVER_NAMESPACE_${TARGET_SDK}})
set(MODS_SUBFOLDER ${MODS_SUBFOLDER_${TARGET_SDK}})
set(INSTALL_TO_GAME_FOLDER ${INSTALL_TO_GAME_FOLDER_${TARGET_SDK}})
set(PROJECT_UPDATE_SERVER "${PROJECT_UPDATE_SERVER_BASE}/${UPDATE_SERVER_NAMESPACE}/${PROJECT_NAME}/")
cmake_path(SET GAME_FOLDER_NORMALIZED NORMALIZE ${GAME_FOLDER_${TARGET_SDK}})
cmake_path(APPEND GAME_FOLDER_NORMALIZED ${GAME_EXECUTABLE_${TARGET_SDK}} OUTPUT_VARIABLE GAME_EXECUTABLE)
cmake_path(APPEND GAME_FOLDER_NORMALIZED ${GAME_WORKING_DIRECTORY_${TARGET_SDK}} OUTPUT_VARIABLE GAME_WORKING_DIRECTORY)
cmake_path(APPEND GAME_WORKING_DIRECTORY ${MODS_SUBFOLDER_${TARGET_SDK}} OUTPUT_VARIABLE MODS_FOLDER)
cmake_path(APPEND MODS_FOLDER "${PROJECT_NAME}" OUTPUT_VARIABLE MOD_FOLDER)
cmake_path(APPEND MODS_SUBFOLDER "${PROJECT_NAME}" OUTPUT_VARIABLE MOD_FOLDER_RELATIVE)

add_library(${MOD_TARGET} SHARED)
target_link_libraries(${MOD_TARGET} PRIVATE ${TARGET_SDK}-sdk detours windowsapp)
target_compile_features(${MOD_TARGET} PRIVATE cxx_std_20)
target_compile_options(${MOD_TARGET} PRIVATE /permissive-)
target_compile_definitions(${MOD_TARGET}
    PRIVATE
        PROJECT_BINARY_FILENAME=$<TARGET_FILE_NAME:${MOD_TARGET}>
        PROJECT_NAME="${PROJECT_NAME}"
        PROJECT_AUTHOR="${PROJECT_AUTHOR}"
        PROJECT_DESCRIPTION="${PROJECT_DESCRIPTION}"
        PROJECT_LONG_DESCRIPTION="${PROJECT_LONG_DESCRIPTION}"
        PROJECT_COPYRIGHT="${PROJECT_COPYRIGHT}"
        PROJECT_AUTHOR_URL="${PROJECT_AUTHOR_URL}"
        PROJECT_UPDATE_SERVER="${PROJECT_UPDATE_SERVER}"
        PROJECT_BUILD_DATE="${PROJECT_BUILD_DATE}"
        PROJECT_VERSION=${PROJECT_VERSION}
        PROJECT_VERSION_MAJOR=${PROJECT_VERSION_MAJOR}
        PROJECT_VERSION_MINOR=${PROJECT_VERSION_MINOR}
        PROJECT_VERSION_PATCH=${PROJECT_VERSION_PATCH}
        PROJECT_TARGET_SDK="${TARGET_SDK}"
        PROJECT_TARGET_SDK_${TARGET_SDK}=1
        PROJECT_MOD_FOLDER="${MOD_FOLDER_RELATIVE}"
)
set_target_properties(${MOD_TARGET}
    PROPERTIES
        OUTPUT_NAME ${PROJECT_NAME}
        VS_DEBUGGER_COMMAND ${GAME_EXECUTABLE}
        VS_DEBUGGER_WORKING_DIRECTORY ${GAME_FOLDER_NORMALIZED}
)

add_subdirectory(src)
configure_file(mod.ini.in mod.ini)
configure_file(mod_version.ini.in mod_version.ini)

set_property(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} PROPERTY VS_STARTUP_PROJECT ${MOD_TARGET})

install(TARGETS ${MOD_TARGET} RUNTIME DESTINATION "${CMAKE_CURRENT_BINARY_DIR}/artifacts/${PROJECT_NAME}")
install(DIRECTORY resources/common/ DESTINATION "${CMAKE_CURRENT_BINARY_DIR}/artifacts/${PROJECT_NAME}")
install(DIRECTORY resources/${TARGET_SDK}/ DESTINATION "${CMAKE_CURRENT_BINARY_DIR}/artifacts/${PROJECT_NAME}")
install(FILES ../LICENSE.txt ../CHANGELOG.md "${CMAKE_CURRENT_BINARY_DIR}/mod.ini" DESTINATION "${CMAKE_CURRENT_BINARY_DIR}/artifacts/${PROJECT_NAME}")

install(CODE "
    file(MAKE_DIRECTORY \"${CMAKE_CURRENT_BINARY_DIR}/archives\")
    execute_process(
        COMMAND \$\{CMAKE_COMMAND} \"-E\" \"tar\" \"cvf\" \"${CMAKE_CURRENT_BINARY_DIR}/archives/${PROJECT_NAME}-${TARGET_SDK}-v${PROJECT_VERSION}.zip\" \"--format=zip\" \"${PROJECT_NAME}\"
        WORKING_DIRECTORY \"${CMAKE_CURRENT_BINARY_DIR}/artifacts\"
    )
")

if(INSTALL_TO_GAME_FOLDER)
    if(INSTALL_TO_GAME_FOLDER_${TARGET_SDK})
        install(TARGETS ${MOD_TARGET} RUNTIME DESTINATION "${MOD_FOLDER}")
        install(DIRECTORY resources/common/ DESTINATION "${MOD_FOLDER}")
        install(DIRECTORY resources/${TARGET_SDK}/ DESTINATION "${MOD_FOLDER}")
        install(FILES ../LICENSE.txt ../CHANGELOG.md "${CMAKE_CURRENT_BINARY_DIR}/mod.ini" DESTINATION "${MOD_FOLDER}")
    endif()
endif()

if(DEFINED UPDATE_SERVER_PATH_NORMALIZED)
    cmake_path(APPEND UPDATE_SERVER_PATH_NORMALIZED "${UPDATE_SERVER_NAMESPACE}/${PROJECT_NAME}" OUTPUT_VARIABLE UPDATE_SERVER_MOD_FOLDER)

    install(TARGETS ${MOD_TARGET} RUNTIME DESTINATION ${UPDATE_SERVER_MOD_FOLDER})
    install(DIRECTORY resources/common/ DESTINATION ${UPDATE_SERVER_MOD_FOLDER})
    install(DIRECTORY resources/${TARGET_SDK}/ DESTINATION ${UPDATE_SERVER_MOD_FOLDER})
    install(FILES ../LICENSE.txt ../CHANGELOG.md "${CMAKE_CURRENT_BINARY_DIR}/mod.ini" "${CMAKE_CURRENT_BINARY_DIR}/mod_version.ini" DESTINATION ${UPDATE_SERVER_MOD_FOLDER})

    install(CODE "
        file(GLOB_RECURSE UPDATE_SERVER_FILES LIST_DIRECTORIES false RELATIVE \"${UPDATE_SERVER_MOD_FOLDER}\" \"${UPDATE_SERVER_MOD_FOLDER}/*\")
        list(REMOVE_ITEM UPDATE_SERVER_FILES \"mod_files.txt\" \"mod_version.ini\")
        list(TRANSFORM UPDATE_SERVER_FILES PREPEND \"add \")
        list(JOIN UPDATE_SERVER_FILES \"\\n\" UPDATE_SERVER_MOD_FILES_CONTENT)
        file(WRITE \"${UPDATE_SERVER_MOD_FOLDER}/mod_files.txt\" \"\${UPDATE_SERVER_MOD_FILES_CONTENT}\\n\")
    ")
endif()
